<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Question::insert([

            ////// PART 1 ////////
            ["exercise_id" => "1", "prompt" => "Human beings are not the only creatures that like to <strong>(0) ______</strong> fun. Many animals play, as do some birds. However, no other creatures spend so much time enjoying themselves as human beings do. Indeed, we <strong>(1) ______</strong> onto our sense of fun right into adulthood.<br><br>  So why do human beings spend so much time playing? One reason is that we have time for leisure; animals have very little time to play as most of their life is spent sleeping and <strong>(2) ______</strong> food.<br><br>  So, is play just an opportunity for us to <strong>(3) ______</strong> in enjoyable activities, or does it have a more important <strong>(4) ______</strong>? According to scientists, <strong>(5) ______</strong> from being fun, play has several very real <strong>(6) ______</strong> for us – it helps our physical, intellectual, and social development. It also helps to <strong>(7) ______</strong> us for what we have not yet experienced. With very <strong>(8) ______</strong> risk, we can act out what we would do in unexpected, or even dangerous, situations.", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => true, "created_at" => now()],
            ["exercise_id" => "2", "prompt" => "<p>After a short time living in a foreign country, I noticed conversations with locals assumed a <strong>(0)........ </strong>pattern. There were standard answers to the usual questions. Most questions caused little <strong>(1).........</strong> - it was rather like dancing, where both partners know how to avoid <strong>(2)..........</strong> on each other's toes.</p><p><br></p><p>But, 'When are you going home?' was a question I <strong>(3).........</strong> to answer, whenever I <strong>(4)..........</strong> my life and the direction it seemed to be <strong>(5)..........</strong> . In the last ten years, I had lived in a dozen countries. And I had travelled through dozens more; usually in <strong>(6).........</strong> of a purpose or a person; occasionally to see the attractions.</p><p><br></p><p>This kind of travel is not <strong>(7).........</strong> wandering, but is the extensive exploration of a wide <strong>(8)........... </strong>of cultures. However, it doesn't allow you to put down roots. At the back of your mind, though, is the idea of home, the place you came from.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => true, "created_at" => now()],
            ["exercise_id" => "3", "prompt" => "<p>The editors of a new online dictionary are <strong>(0)........</strong> the public to submit words that they would like to see in the dictionary. People are already sending in words, some of which they have <strong>(1).........</strong> themselves - these will almost certainly not <strong>(2).........</strong> in the dictionary!</p><p><br></p><p>When a new word is submitted, editors check newspapers, radio, television and social networks to see how <strong>(3)........</strong> the word is used. They also <strong>(4)........ </strong>whether the word is likely to remain in use for more than one or two years. The evidene they collect will help them decide whether or not to put it in the dictionary.</p><p><br></p><p>Editors will <strong>(5)......... </strong>feedback on any words submitted by the public. Even words not accepted will <strong>(6)......... </strong> to be monitored over the following year. Editors need to be <strong>(7).........</strong> of new words which emerge from areas such as popular culture and technology, so that their dictionary is a genuine <strong>(8)......... </strong>of the current language. </p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => true, "created_at" => now()],
            ["exercise_id" => "4", "prompt" => "<p>Memory is at the <strong>(0).........</strong> of our sense of personal identity. If we did not have memory, we would not be <strong>(1).........</strong> of our relationships with other people and would have no <strong>(2)......... </strong>that we had had any past at all. And without memory we would have no knowledge on which to <strong>(3).........</strong> our present and future.</p><p><br></p><p>Memory <strong>(4)......... </strong>of three processes: registration, retention and recall. Registration when we consciously notice something. Retention is the next <strong>(5).........</strong> , when we keep something we have noticed in our minds for a certain period of time. Finally, recall occurs when we actively think about some of these things that are <strong>(6).........</strong> in our minds.</p><p><br></p><p>Every day we are subjected to a vast <strong>(7)........ </strong>of information. If we remembered every <strong>(8).........</strong> that we had ever seen or heard, life would be impossible. Consequently, our brains have learnt to register only what is of importance.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => true, "created_at" => now()],
            ["exercise_id" => "5", "prompt" => "<p>Official figures show that the number of people <strong>(0).........</strong> international flights is decreasing, and this is <strong>(1).........</strong> in significant changes to holidaying habits.</p><p><br></p><p>As the cost of air tickets increases, it appears that more and more families are choosing to <strong>(2).........</strong> their summer holidays at home. People are also becoming more <strong>(3).........</strong> of the harm that flying does to the environment, and see it as a way of helping to <strong>(4).........</strong> the planet, too.</p><p><br></p><p>For many parents a summer with no airport queues or overcrowded resorts may seem attractive, but the idea might well be less <strong>(5).........</strong> with their teenage children, who are probably <strong>(6).........</strong> to flying off to the Mediterranean of Miami as soon as school breaks up. So, the question is, how can young people have lots of fun when so much will be closed for the holidays, and so many of their friends are bound to be away?</p><p><br></p><p>The answer may lie at the local sports centre. Nowadays, many centres organise summer activities aimed at young people <strong>(7).........</strong> either on indoor or outdoor sports. These might range, for instance, from playing table tennis to going mountain-biking. As well as being healthy and enjoyable, taking part in activities like these is also an excellent way to <strong>(8).........</strong> new friends. For the most popular activities, though, it is advisable to apply early for a place - perhaps two or three months in advance.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => true, "created_at" => now()],


            /////// PART 2 ///////
            [
                "exercise_id" => "6",
                "prompt" => "Folding bicycles have <strong>(0) .........</strong> around for quite some time now. However, an amazing new
Japanese version <strong>(1) .........</strong> be folded with a swiftness and efficiency never seen before. This bike
is designed <strong>(2) .........</strong> that it is possible to fold it up quickly. Once folded, you pull the bike along <strong>
(3) ........</strong> ease.</br></br>

This remarkable bike has a half-folding frame with a hinge in the middle. And, although the basic idea
is <strong>(4).........</strong> original, its inventor has created an especially clever variation, combining compactness<strong>
(5) ........</strong> convenience with smart design.</br></br>

Recently, folding bicycles <strong>(6) .........</strong> become very popular in Japan, particularly in congested urban
areas like Tokyo, a city <strong>(7) .........</strong> every square centimetre of space is in great demand. Japanese
cyclists need to be able to store their bikes in tiny areas at home or the office. And <strong>(8) .........</strong> they
should want to take their bicycle on the underground, a folding model is a big advantage.",

                "before_prompt" => "null",
                "after_prompt" => "null",
                "is_multiple_choice" => false,
                "created_at" => now()
            ],
            [
                "exercise_id" => "7",
                "prompt" => "In the last few years, a number of cockery schools have been set <strong>(0) .........</strong> in Ireland to promote
Irish cooking. <strong>(9) .........</strong> such school is run by Kathleen Doyle not <strong>(10).....</strong> from the centre
of Dublin.<br>

'I opened the school twelve years ago; says Kathleen. The school was by no means an overnight
success; I found <strong>(11) ........</strong> necessary to work hard to build up a reputation. One of my advantages
was that I'd had problems with my own cooking. I've made <strong>(12) .........</strong> mistake that it's possible to
make, but <strong>(13) .........</strong> of this, I know what people do wrong from first-hand experience.'<br>

Just <strong>(14) .........</strong> most cookery schools in Ireland, Kathleen initially copied the classical dishes of
France and Italy and other countries <strong>(18) .........</strong> have a reputation for excellent food. ‘Now though,
things are changing,’ says Kathleen. ‘We get excellent produce from Irish farms and, <strong>(16) .........</strong>
result, we're encouraging students to create unique irish dishes.",
                "before_prompt" => "null",
                "after_prompt" => "null",
                "is_multiple_choice" => false,
                "created_at" => now()
            ],
            [
                "exercise_id" => "8",
                "prompt" => "It <strong>(0) ........</strong> sometimes said that animals use language. Certainly some animal species have
developed amazingly sophisticated ways of communicating with <strong>(1) .........</strong> another.<br><br>

But there are huge differences between the ways animals communicate and the ways human beings
do, When animals make a sound, such <strong>(2).........</strong> a bark or a call, it is in reaction to <strong>(3) ......</strong>
is happening around them. An alarm call means they are frightened. A hunger call means they
want food. Animals, though, cannot make a call meaning ‘I was scared yesterday’ or ‘I'll be hungry
tomorrow', Only human beings are capable <strong>(4) .........</strong> doing this.<br><br>

Zoologists have had some success in teaching human language to animals. <strong>(5) .........</strong> some
famous experiments, chimpanzees have <strong>(6) .........</strong> taught to use their hands to give information
on a range of things. Some animals have even managed to put signs together in <strong>(7) .........</strong> to make
simple sentences. However, getting them to do this takes a huge <strong>(8).........</strong> of training.",
                "before_prompt" => "null",
                "after_prompt" => "null",
                "is_multiple_choice" => false,
                "created_at" => now()
            ],
            [
                "exercise_id" => "9",
                "prompt" => "Today I am visiting a sweets factory, a building squeezed <strong>(0) .........</strong> a railway line and a canal.
<strong>(1)........</strong> I watch, trucks filled with sugar arrive at the factory where this family-owned company has
been making sweets for some 80 years.<br><br>

Being in a factory <strong>(2)..........</strong> this one is exactly <strong>(3) .........</strong> children dream of. I am staring at huge
vats of sticky liquid <strong>(4) .........</strong> eventually ends up as mouth-watering sweets. Every now <strong>(5) .......</strong>
then I see a factory worker in a white coat put a sweet into her mouth.<br><br>

Ailsa Kelly, granddaughter of the company owner, remembers visiting the factory as <strong>(6)..........</strong> child
with her grandfather. ‘He would take me onto the factory floor and introduce me; she says. ‘He told
me, &quotYou may work here some day.&quot And indeed, she has, continuously, <strong>(7)...............</strong> 1999. The sense
of family is <strong>(8).........</strong> of the reasons employees are remarkably loyal to the company.",
                "before_prompt" => "null",
                "after_prompt" => "null",
                "is_multiple_choice" => false,
                "created_at" => now()
            ],
            [
                "exercise_id" => "10",
                "prompt" => "Tattoos, <strong> (0)......... </strong> some people call 'body art', have become more and more popular in recent years. In <strong> (1)......... </strong> of the pain caused by having a needle make hundreds of holes in their skin, millions of people <strong> (2)......... </strong> vary widely in age and background are nowadays having their bodies decorated with ink in all kinds of ways.<br><br>
Many of today's young people, <strong> (3)......... </strong> parents were the first generation to experiment with tattoos, see it as a way of expressing their individuality, and in <strong> (4)......... </strong> to do this, they are constantly looking for new styles and designs. <strong> (5)......... </strong> to this increasing demand, tattoo studios have appeared in many towns and villages.<br><br>
<strong> (6)......... </strong> people tend to think of it as a modern practice, tattooing has in fact been around for a long time. There is evidence of tattoos being worn in Siberia over 4,000 years ago, as <strong> (7)......... </strong> as in Ancient Egypt at that time, and it is thought to have existed in Japan 10,000 years ago. Even so, it was not until the late 18th century, when Captain James Cook sailed to Polynesia, that Europeans took an interest.<br><br>
It was on the island of Tahiti, <strong> (8)......... </strong> tattooing had an immportant role in society, that Cook and his crew first saw tattooed men and women, and because of that, the English word comes from the Tahitian word tatau. Ever since then, sailors have had tattoos done, often to show the distant places they have visited.",
                "before_prompt" => "null",
                "after_prompt" => "null",
                "is_multiple_choice" => false,
                "created_at" => now()
            ],

            /////// PART 3 ///////
            ["exercise_id" => "11", "prompt" => "Tea is an <strong>(0) ______</strong> popular drink with many people. It is estimated that the consumption of tea in England alone exceeds 165 million cups daily. Despite this, the drink was virtually <strong>(1) ______</strong> in England until about 400 years ago. The first <strong>(2) ______</strong> to tea in England comes in a diary written in 1660. However, its <strong>(3) ______</strong> really took off after the <strong>(4) ______</strong> of King Charles II to Catherine of Braganza. It was her great love of tea that made it <strong>(5) ______ </strong>.<br><br> It was believed that tea was good for people as it seemed to be capable of reviving the spirits and curing certain minor <strong>(6) ______</strong> . It has even been suggested by some historians that it played a significant part in the Industrial Revolution. Tea, they say, increased the number of hours that <strong>(7) ______</strong> could work in factories as the caffeine in tea made them more <strong>(8) ______</strong> and consequently able to work longer hours.", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "12", "prompt" => "<p>Elite <strong>(0).........</strong> like the Jamaican Usain Bolt have regularly been clocked running at nearly 45 kilometres per hour. Such speed would have seemed <strong>(1).........</strong> not so long ago. Scientists now suggest that humans can move <strong>(2).........</strong> faster than even that, perhaps as fast as 65 kilometres per hour.</p><p><br></p><p>For years, it was assumed that simple muscle power determined human speed, but recent research suggest otherwise. The most important <strong>(3).........</strong> factor appears to be how quickly the muscles can contract and thus <strong>(4).........</strong> the time a runner's foot is in contact with the ground.</p><p><br></p><p>Is our athletic ability inherited? Researcher Alun Williams has <strong>(5).........</strong> twenty-three inherited factors that influence sporting performances, such as the <strong>(6).........</strong> use of oxygen, and strength. As world population rises, predicts Williams, the <strong>(7).........</strong> of there being someone with the right genes for these twenty-three <strong>(8).........</strong> will increase noticeably and thus faster runners are likely to emerge in the future.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "13", "prompt" => "<p>I have been a keen <strong>(0).........</strong> for about nine years. When I began cycling, I found the flat roads easy but the hills almost <strong>(1).........</strong> . Surprisingly, now it's the opposite. A long flat ride can be both dull and <strong>(2).........</strong> as you never experience that fantastic feeling of freedom when speeding downhill. Years ago, going uphill left me <strong>(3).........</strong> . Now I have learned to take hills slowly and steadily.</p><p><br></p><p>When I set off, I'm full of energy and the first hundred metres are <strong>(4).........</strong> , the next couple of kilometres are a bit tiring but on the whole the experience is very <strong>(5).........</strong> .</p><p><br></p><p>Cycling is <strong>(6).........</strong> any other forms of exercise I have tried; it is never a chore but always a <strong>(7).........</strong> . The physical benefits are obvious but the mental benefits are <strong>(8).........</strong> important; when you are travelling calmly at a sensible speed, you breathe fresh air, have time to think and can relax.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "14", "prompt" => "<p>Most people feel rather <strong>(0).........</strong> when they go for an interview for a new job. This is not surprising as getting a job one wants is important. People being interviewed expected the interviewers to be <strong>(1).........</strong> , matching an applicant against a job <strong>(2).........</strong> . However, what often happens in reality is that the interviewers make <strong>(3).........</strong> that are little more than reactions to the <strong>(4).........</strong> of the applicant.</p><p><br></p><p>Even skilled interviewers may, without realisig it, <strong>(5).........</strong> favour people who make them feel at <strong>(6).........</strong> . With this in mind, if you go for an interview you should try to make a good impression from the start by presenting the interviewers with the very best version of yourself, emphasising the <strong>(7).........</strong> of skills you have. You must appear very positive and as <strong>(8).........</strong> as possible. It is for you to convince the interviewers that you are definitely the most suitable person for the job.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "15", "prompt" => "<p>According to experts, doing puzzles keeps our brains fit and <strong>(0).........</strong> . As well as gaining <strong>(1).........</strong> from finding the correct answer to a difficult problem, we give our brains a good workout in the process. To help us do this, all sorts of handheld 'brain games' are now available in the shops, and the most <strong>(2).........</strong> games have sold in their millions.</p><p><br></p><p>What's more, people <strong>(3).........</strong> that the more they play the games, the easier it is to find <strong>(4).........</strong> to the problems posed. They see this as proof that there has been an <strong>(5).........</strong> in the power of their brains. Unfortunately, however, this may be a false impression.</p><p><br></p><p>Some <strong>(6).........</strong> argue that the brain gets better at any task the more often  it is repeated. In other words, the improvement in the <strong>(7).........</strong> of the brain is something that happens naturally.</p><p><br></p><p>So although these brain games are obviously fun to play, it remains <strong>(8).........</strong> whether they are actually helping to boost brainpower or not.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => false, "created_at" => now()],

            /////// PART 4 ///////
            ["exercise_id" => "16", "prompt" => "They didn't sell many programmes at the match.", "before_prompt" => "Very", "after_prompt" => "at the match last Saturday.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "16", "prompt" => "We got to work late because we decided to drive rather than take the train.", "before_prompt" => "We got to work late because we decided to drive", "after_prompt" => "the train.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "16", "prompt" => "Last Friday was the first time my car ever broke down, even though it is very old.", "before_prompt" => "Until last Friday, my car", "after_prompt" => "down, even though it is very old.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "16", "prompt" => "All your complaints will be investigated by my staff tomorrow, said the bank manager.", "before_prompt" => "The bank manager promised that his staff", "after_prompt" => "all our complaints the next day.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "16", "prompt" => "Last year the heavy rain caused the postponement of the tennis tournament.", "before_prompt" => "Last year the tennis tournament", "after_prompt" => "so heavily.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "16", "prompt" => "Jack does not want to work for his uncle any longer.", "before_prompt" => "John does not want", "after_prompt" => "for his uncle.", "is_multiple_choice" => false, "created_at" => now()],

            ["exercise_id" => "17", "prompt" => "Robert had never been to Turkey on business before...", "before_prompt" => "It", "after_prompt" => "Robert had ever been to Turkey on business.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "17", "prompt" => "It was impossible for me to know which road to follow", "before_prompt" => "I", "after_prompt" => "known which road to follow", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "17", "prompt" => "So far this year the cost of petrol has not increased.", "before_prompt" => "So far this year there", "after_prompt" => "in the cost of petrol.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "17", "prompt" => "I cannot get all my clothes in the suitcase.", "before_prompt" => "The suitcase", "after_prompt" => "take all my clothes.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "17", "prompt" => "The waiter carried the tray very carefully so that he wouldn't spill any of the drinks.", "before_prompt" => "The waiter carried the tray very carefully so", "after_prompt" => "any of the drinks.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "17", "prompt" => "I wasn't able to get to the airport on time because of the bad weather.", "before_prompt" => "The bad weather", "after_prompt" => "to the airport on time.", "is_multiple_choice" => false, "created_at" => now()],


            ["exercise_id" => "18", "prompt" => "My brother doesn't play tennis now as well as he used to.", "before_prompt" => "My brother used to", "after_prompt" => "does now.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "18", "prompt" => "Clothing companies are selling an increasing number of goods on the internet.", "before_prompt" => "An increasing number of goods", "after_prompt" => "clothing companies on the internet.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "18", "prompt" => "'Well done for scoring twice, Mark' said the coach.", "before_prompt" => "Mark", "after_prompt" => "for scoring twice.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "18", "prompt" => "You are welcome to contact me if you need more information.", "before_prompt" => "Please feel free", "after_prompt" => "me if you need more information.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "18", "prompt" => "Tickets for the concert cannot be bought before 12th May.", "before_prompt" => "Tickets for the concert will not", "after_prompt" => "12th May.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "18", "prompt" => "I didn't buy the camera because it was so expensive.", "before_prompt" => "I would have bought the camera", "after_prompt" => "so expensive.", "is_multiple_choice" => false, "created_at" => now()],

            ["exercise_id" => "19", "prompt" => "'Do you know the cost of the trips?' asked Pamela.", "before_prompt" => "Pamela asked if I knew", "after_prompt" => "were.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "19", "prompt" => "During the quiz, I could not think of the correct answer to the winning question.", "before_prompt" => "During the quiz, I was not", "after_prompt" => "the correct answer to the winning question.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "19", "prompt" => "I promised that I would think  carefully about the job offer.", "before_prompt" => "I promised", "after_prompt" => "the job offer.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "19", "prompt" => "The group continued to walk despite rain starting to fall.", "before_prompt" => "The group carried", "after_prompt" => "started to rain.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "19", "prompt" => "Almost all the tickets for next Saturday's concert have been sold.", "before_prompt" => "There are", "after_prompt" => "for next Saturday's concert.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "19", "prompt" => "Do you think it is likely that Peter will get the job he has applied for?", "before_prompt" => "Do you think that Peter has", "after_prompt" => "the job he has applied for?", "is_multiple_choice" => false, "created_at" => now()],

            ["exercise_id" => "20", "prompt" => "In 2009 I went to Shanghai and I will never forget it.", "before_prompt" => "I", "after_prompt" => "to Shanghai in 2009.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "20", "prompt" => "It was foolish of you to ride your bike so fast.", "before_prompt" => "You", "after_prompt" => "your bike so fast.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "20", "prompt" => "There was no point in staying at the part because my friends had left.", "before_prompt" => "My friends had left the party so", "after_prompt" => "there.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "20", "prompt" => "It's possible that the thieves hid the money in the countryside.", "before_prompt" => "The thieves", "after_prompt" => "the money in the countryside.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "20", "prompt" => "The climbers continued to go up the mountain even though it was snowing.", "before_prompt" => "The climbers", "after_prompt" => "the mountain even though it was snowing.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "20", "prompt" => "There isn't much chance of the weather improving today.", "before_prompt" => "The weather", "after_prompt" => "today.", "is_multiple_choice" => false, "created_at" => now()],


            //New questions 25-05-25
            ["exercise_id" => "21", "prompt" => "<p>People's fingernails and toenails, <strong>(0)........</strong> to a recent study, are nowadays growing more quickly. Research <strong>(1)........</strong> out at the University of North Carolina indicates that the speed at which human nails are growing has increased by <strong>(2)........</strong> to 25 per cent over the last 70 years.</p><p><br></p><p>The results of the study show that the <strong>(3)........</strong> human fingernail now grows about 3.5 mm a month, compared with just 3 mm seven decades ago. Toenail growth, <strong>(4)........</strong> only about 2 mm per month, was also up on the figure obtained in a similar survey done 70 years ago.</p><p><br></p><p>Researchers  put the rapid increase down to changes in lifestyle, particularly the greater <strong>(5)........</strong> awareness of the importance of regular exercise and a healthy diet. This, they point out, is in <strong>(6)........</strong> with similar trends in the height and weight of present-day adults.</p><p><br></p><p>Interestingly, it appears that nails <strong>(7)........</strong> to grow fastest in warmer conditions, with the quickest growth <strong>(8)........</strong> among young people, and men. The fastest-growing nail is on the middle finger, while that on the little finger is by far the slowest, at only a fraction over 3 mm each month.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => true, "created_at" => now()],
            ["exercise_id" => "22", "prompt" => "<p>Nowadays, one of the most <strong>(0)........</strong> items found in the home is the sticking plaster.</p><p><br></p><p>Protecting a cut by covering the affected area with a piece of material that sticks to the skin may seem a rather <strong>(1)........</strong> idea, so it is perhaps surprising to learn that the plaster was not <strong>(2)........</strong> until about ninety years ago.</p><p><br></p><p>The person who thought <strong>(3)........</strong> the idea was Earle Dickson, an employee of the Johnson &amp; Johnson company. Concerned that his wife Josephine sometimes <strong>(4)........ </strong>accidents while cooking and doing other jobs, he used pieces of cotton material placed inside strips of sticky tape to cover her injuries. This prevented dirt getting into the wound and protected it from further harm as she did the housework.</p><p><br></p><p>Dickson's boss was impressed, so in 1921 Johnson &amp; Johnson put the sticking plaster into <strong>(5)........</strong> under the brand name Band-Aid. Sales at first were slow, but somebody at the company came up with the birhgt idea of giving free plasters to the Boy Scouts. The created publicity and from then <strong>(6)........</strong> it became a commercial success. DIckson was promoted within the company, eventually becoming a senior executive.</p><p><br></p><p>Although the basic design of the sticking plaster has remained similar to the <strong>(7)........ </strong>, there have been many developments in the materials used and it is now <strong>(8)........</strong> in a variety of shapes, sizes and colours. Total worldwide sales are believed to have exceeded 100 billion.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => true, "created_at" => now()],
            ["exercise_id" => "23", "prompt" => "<p>Years ago, <strong>(0)........</strong> in the days when I was just a kid, my family used to have Sunday picnics together in a <strong>(1)........</strong> part of the countryside. We would find a suitable quiet and pleasant <strong>(2)........</strong> , then spend several hours chatting, eating and playing games in the open air. Since then, though, my parents' life has become so much busier and they never seem to have the time for <strong>(3)........</strong> family meals any more.</p><p><br></p><p>In my <strong>(4)........</strong> this is a great pity, so I've recently started to organise picnics of my own. I get in touch with some of my closest firends and first we <strong>(5)........</strong> a suitable place to go. Then we'll talk abouot who'll bring which food. This ensures that there will be a variety of tasty things to eat, particularly <strong>(6)........ </strong>everyone makes the meals they do best. It's important, though, to keep the food simple, as everything has to fit into a backpack and then be carried across fields and up river valleys.</p><p><br></p><p>When we finally <strong>(7)........</strong> our destination, it's time to sit down, relax and enjoy each other's company. And I'm <strong>(8)........</strong> certain that food tastes far better on a picnic than anywhere else!</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => true, "created_at" => now()],
            ["exercise_id" => "24", "prompt" => "<p>A recent survey <strong>(0)........</strong> that office workers are suffering from an increasingly common 21st-century problem: too many emails. The study, which involved observing the <strong>(1)........</strong> of over 50 companies, appears to show huge number of messages they are now receiving is <strong>(2)........</strong> many of them from doing their jobs properly. In some cases, <strong>(3)........</strong> to the authors of the report, the negative effect on concentration can be as bad as losing a whole night's sleep.</p><p><br></p><p>The main problem seems to be that whenever employees receive emails, they feel obliged to reply to them immediately. Often the message has nothing at all to <strong>(4)........</strong> with the work they are currently involved in, requiring them to focus on a completely different issue - until the next email arrives. These constant changes are tiring for the brain and this inevitably <strong>(5)........</strong> to poor overall performance.</p><p><br></p><p>Many employees continue to do this outside working hours, checking their emails at home again and again just in <strong>(6)........</strong> there are any new messages. Some even do so while they are on holiday.</p><p><br></p><p>The solution, say the scientists who carried out the survey, is relatively simple. Companies should advise people to check their emails far less often, possibly as <strong>(7)........</strong> as three or four times a day, reminding them that not every message needs an instant reply. They could also encourage their employees to relax more, and not <strong>(8)........</strong> their work quite so seriously.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => true, "created_at" => now()],
            ["exercise_id" => "25", "prompt" => "<p>The island of St Lucia, which <strong>(0)........ </strong>between St Vincent and Martinique, is said to be one of the most attractive in the Caribbean. Measuring 44 kilometres long and 22 kilometres in width, it has a central mountain range which runs the length of the island. There are white sandy beaches with wonderful <strong>(1)........</strong> of the two tall volcanoes called the Pitons, <strong>(2)........</strong> of which are covered - like most of the island - in dense forest.</p><p><br></p><p>The climate is hot and tropical <strong>(3)........</strong> the year, with average daily temperatures of about 27ºC. Showers can occur in any month, although they are usually <strong>(4)........ </strong>fairly quickly.</p><p><br></p><p>Not surprisingly, St Lucia is extremely <strong>(5)........ </strong>with tourists. There is a wide range of accommodation, from camping to luxury hotels, and it is very well connected by sea and air with the rest of the world. <strong>(6)........</strong> this, the island remains largely unspoilt and there are many quiet places to visit.</p><p><br></p><p>Not far from the coastal areas there are beautiful waterfalls in spectacular green valleys, often with <strong>(7)........</strong> anyone else about. The roads are narrow and winding, so it is not advisable to travel any distance by car. A much better way to <strong>(8)........</strong> to know the countryide of this lovely island is on horseback.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => true, "created_at" => now()],
           
           
            ["exercise_id" => "26", "prompt" => "<p>The very first Tour de France, the greatest cycle race <strong>(0)........ </strong>the world, was held in 1903. It began when two French journalists, Henri Desgrange and Géo Lefévre, came <strong>(1)........</strong> the idea of a race right round the country, <strong>(2)........</strong> that had never been tried anywhere before.</p><p><br></p><p>Nowadays we might think the aim of such<strong> </strong>an idea would to bring in lots of television money, or even tourists, but at the beginning of the twentieth century what they wanted to do <strong>(3)........</strong> sell more copies of their newspaper. And they succeeded. Circulation figures, <strong>(4)........</strong> had been 25,000, went to 65,000 within a year, and on to half a million by 1923.</p><p><br></p><p>The reporters were in fact quite closely involved in organising the race, and Desgrange would go <strong>(5)........</strong> to remain Tour Director from 1903 right up to 1939. Even so, their inicial design for the race changed in several important ways before the first one was run. For instance, they had intended it to be held over five weeks, but such a long race was just too much for most riders and very <strong>(6)........</strong> wanted to take part.</p><p><br></p><p>So it became half <strong>(7)........</strong> length, and it would be run entirely in July <strong>(8)........</strong> than from late May to early July. As, however, it would still go right round France, the distance travelled each day would be much longer, with cyclists sometimes having to ride at night.  </p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "27", "prompt" => "<p>The Red Sea coast of Egypt is surely one of the best places <strong>(0)........ </strong>the world to go underwater diving. Its hot sunny climate and clear warm water make it the ideal place for beginners as <strong>(1)........ </strong>as for experienced divers, at any time of the year.</p><p><br></p><p><strong>(2)........</strong> over fifty diving centers in the area, many different types of diving are possble. At centres for complete beginners there are training courses <strong>(3)........</strong> include simple dives with a qualified instructor. These dives <strong>(4)........ </strong> them used to being underwater and teach some basic skills such as swimming and breathing below the surface.</p><p><br></p><p>More experienced divers can choose from a vast range of possible activities and many of these can be enjoyed <strong>(5)........</strong> as part of a group or, if they prefer, alone. Some like to explore the coast of the National Park, where the steep cliffs extend underwater to a depth of more than seventy metres. For dives of <strong>(6)........</strong> kind it is advisable to be accompanied by a guide, on <strong>(7)........</strong> of the strong currents which can suddenly change direction.</p><p><br></p><p>For really advanced divers, thre are some fascinating wrecks at the bottom of the Red Sea. <strong>(8)........</strong> visits to these old ships require quite long boat trips, it is well worth going just to see the huge variet of beautfil plants and fish down there.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "28", "prompt" => "<p>Camping in the countryside is usually great fun, but sometimes things can <strong>(0)........</strong> wrong. Accidents can happen, so it is essential to think about safety both before you go and while you are there. This will prevent your fun camping trip turning <strong>(1)........</strong> something less pleasant.</p><p><br></p><p>Firstly, you need to plan ahead. Check out the weather forecast a few days <strong>(2)........</strong> advance and watch out for any reports of fires in the area you are thinking <strong>(3)........</strong> going to. Prepare an emergency kit in case you or anyone with you has an accident or illness while you are there.</p><p><br></p><p>Choose your campsite carefully, avoiding any places <strong>(4)........</strong> there is a risk of flooding. Before you put up your tent, make sure there are no sharp objects on the ground, or ants' or wasps' nests nearby.</p><p><br></p><p>In <strong>(5)........</strong> to keep insects out of the tent, close it whenever you go in or out. If you need a camp fire for cooking, be careful <strong>(6)........</strong> to build it anywhere near your tent, and before you go to bed, remember to put it <strong>(7)........</strong> completely, preferably with lots of water.</p><p><br></p><p>After meals, pick up any bits of food that could be left on the ground, as these can attract insects - or larger creatures. It also makes sense, for <strong>(8)........</strong> same reason, to keep unused food in closed containers well away from the camp. You don't want a hungry bear or other animal suddenly appearing in your tent!</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "29", "prompt" => "<p>Nowadays, just about everyone has a mobile phone. This wonderful invention enables people to stay <strong>(0)........</strong> touch with others at any time of day or night and no <strong>(1)........</strong> where they are. It has brought people closer and it <strong>(2)........</strong> certainly have saved many lives by enabling immediate contact with the emergency services.</p><p><br></p><p>It also, on the other hand, has its disadvantages. Perhaps the most obvious of all is the sound of people talking loudly into their phones on public transport, apparently unaware <strong>(3)........</strong> how much they are disturbing other travellers. This is now starting to happen on aeroplanes, where until recently passengers <strong>(4)........</strong> always told to keep their cell phones switched off.</p><p><br></p><p>Quite <strong>(5)........</strong> from the annoyance they cause, those who shout into their phones in public may also be taking unnecessary risks. It is amazing <strong>(6)........</strong> often people talk about highly personal subjects, including money matters, when they have no idea who might be listening to their every word.</p><p><br></p><p>Finally, there is the sound of other people's ringtones, all too often <strong>(7)........</strong> maximum volume. The owner of the phone may think their choice of music is cool, but everyone around them probably just wishes they <strong>(8)........ </strong>turn it down - or off.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "30", "prompt" => "<p>Surely, <strong>(0)........</strong> of the most amazing sights on Earth is the display of natural light in the night sky known <strong>(1)........</strong> the Northern Lights. It is something everyone should see at least once in their life.</p><p><br></p><p>These lights, <strong>(2)........</strong> are mainly visible in the Arctic region, are caused when material from the sun reaches the Earth's magnetic field. On the <strong>(3)........</strong> the most common colours are green and red, although sometimes blue or purple lights can be seen. They often look <strong>(4)........</strong> brightly coloured clouds dancing across the sky, in displays that can last several hours.</p><p><br></p><p><strong>(5)........</strong> you want to observe the Northern Lights, it's best to get as close to the North Pole as possible during the winter, in <strong>(6)........</strong> of the extreme cold. Seeing the lights in the short Arctic summer is not really possible in view of the fact that they are only visible in darkness, and during the months when the sun never sets there is daylight 24 hours a day.</p><p><br></p><p>Weather conditions <strong>(7)........</strong> a big difference. The lights cannot be see <strong>(8)........</strong> the sky is clear, so there must be no fog or heavy clouds. Bright moonlight can also reduce the intensity of the lights and because of this you should avoid any nights that have a full moon.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => false, "created_at" => now()],
            
            ["exercise_id" => "31", "prompt" => "<p>The <strong>(0)........ </strong>city of Miami was founded in 1896 by Julia Tuttle, a wealth Florida businesswoman. From a population then of just 300, it has become a vat urban area of 5.5 million <strong>(1)........ </strong>, attracting <strong>(2)........</strong> from all over the world. Its excelling transport links mean it can <strong>(3)........</strong> be reached by road, rail, air or sea.</p><p><br></p><p>The city's continuing <strong>(4)........</strong> as a tourist and financial centre has led to a construction boom. Many of the new building are over 120 metres in height, giving Miami the most impressive skyline in the country after New York and Chicago.</p><p><br></p><p>Its wide variety of <strong>(5)........</strong> includes sandy beaches, nightclubs, music and dancing, as well as activites such as skateboarding and cycling in the world-famous, <strong>(6)........</strong> South Beach area. The city centre has a number of <strong>(7)........</strong> parks and gardens, and of course there is the wonderful weather; <strong>(8)........</strong> any other major city in the USA, it has a genuinely tropical climate.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "32", "prompt" => "<p>Riding in a hot-air balloon is a <strong>(0)........ </strong>calm and peaceful expreience, quite <strong>(1)........</strong> any other form of flying. With no engines to provide power, a balloon depends <strong>(2)........</strong> on the winds around it to move in any direction <strong>(3)........ </strong>, the maximum speed is normally around 15 kilometres per hour.</p><p><br></p><p>This kind of balloon is based on the simple scientific principle that the <strong>(4)........</strong> of hot air is less than that of cold air. It is not, however, a large difference, as a cubic metre of hot air is only about 250 grams lighter than the same amount of cold air. This means it takes <strong>(5)........ </strong>four cubic metres of hot air just to lift one kilo, which explains why balloons that carry people have to be so enormous.</p><p><br></p><p>A gas burner is used to <strong>(6)........</strong> the air inside the balloon, causing it to rise. To go up more slowly, or to make a <strong>(7)........</strong> , hot air is released from the top of the balloon. The fact that the wind blows in different directions at different heights <strong>(8)........</strong> the pilot to steer the balloon left or right by moving it to higher or lower positions in the sky.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "33", "prompt" => "<p>Most <strong>(0)........</strong> agree that surfing began centuries ago in the Hawaii Islands in the Pacific Ocean, where the <strong>(1)........</strong> regarded it as an important part of their culture, not as a recreational <strong>(2)........</strong> . It was not until the early 20th century that it achieved <strong>(3)........</strong> as a sport, and for many years it remained  <strong>(4)........</strong> to see surfers anywhere other than in three main locations - Hawaii, California and Australia.</p><p><br></p><p>All that began to change in the 1960s, partly as a result of <strong>(5)........</strong> in the design of surfboards, but also because of the success of films and pop bands, <strong>(6)........</strong> The Beach Boys, that were associated with surfing culture. Since then there has been rapid growth in the popularity of surfing throughout the world, and for many surfers it has become a highly <strong>(7)........</strong> sport that requires skill and courage to deal with the <strong>(8)........</strong> conditions in some of the roughest seas on Earth.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "34", "prompt" => "<p>A woman living in the city centre has asked for <strong>(0)........</strong> to find a bigger house and garden - so that her 112 pets can live in less <strong>(1)........</strong> conditions. Jennifer Symons, 26, has always loved animals and now has a <strong>(2)........</strong> that includes twelve cats, seven dogs, four monkeys, two horses and a <strong>(3)........</strong> of smaller creatures, including hamsters, parrots and tropical fish.</p><p><br></p><p>She also has a number of snakes, and although none of them, she says, is <strong>(4)........</strong> , some of her neighbours in Lower Market Street remain <strong>(5)........</strong> and are worried that they might escape. Generally, though, people seem to like Jennifer's pets and are always friendly towards her.</p><p><br></p><p>All these animals, however, have to be looked after, and Jennifer has to get up at 5.30 every morning to start <strong>(6)........</strong> some of them. Cleaning and other tasks take up so much time that taking care of them has now become almost her main <strong>(7)........</strong> , leaving her with only her earnings from a part-time job at a local supermarket to maintain the 112 and herself. It is hardly <strong>(8)........</strong> , therefore, that she can't really afford to move into a bigger house.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "35", "prompt" => "<p>A massive clean-up <strong>(0)........</strong> is now under way in the south-west of the country after a powerful storm unexpectedly struck the region. Among the worst affected were <strong>(1)........</strong> areas, where many small boats were sunk or destroyed, though, <strong>(2)........</strong> , there are no reports of anyone missing of seriously injured.</p><p><br></p><p>In many towns, however, there was <strong>(3)........</strong> damage to property, with trees and fences blown over. In one street, almost every house had its roof blown off, leaving many families <strong>(4)........</strong> until repairs can be carried out. The windy conditions also affected transport links leading to the closure of motorways and the <strong>(5)........</strong> of nearly all rail services.</p><p><br></p><p>Further inland, where the monthly average <strong>(6)........</strong> is about 80mm, over 100mm fell in just a few hours. This resulted in several rivers bursting their banks and flooding huge areas of <strong>(7)........</strong> land. Some villages were <strong>(8)........</strong> cut off by the rapidly rising water, although communications have now been restored in most places.</p>", "before_prompt" => "null", "after_prompt" => "null", "is_multiple_choice" => false, "created_at" => now()],
            
            ["exercise_id" => "36", "prompt" => "I regret not buying that bike when I had the chance.", "before_prompt" => "I", "after_prompt" => "that bike when I had the chance.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "36", "prompt" => "In spite of the heavy snow, we managed to get home quickly.", "before_prompt" => "We managed to get home quickly,", "after_prompt" => "heavily.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "36", "prompt" => "'Did you see that film on Friday night?' Sean asked me.", "before_prompt" => "Sean wanted to know", "after_prompt" => "that film on Friday night.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "36", "prompt" => "I'm afraid you're not old enough to travel abroad ", "before_prompt" => "You're not old enough to travel abroad", "after_prompt" => "I'm afraid.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "36", "prompt" => "Jenny rang because she was worried about us.", "before_prompt" => "Jenny", "after_prompt" => "she hadn't been worried about us.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "36", "prompt" => "Have they repaired your computer yet?", "before_prompt" => "Have", "after_prompt" => "yet?", "is_multiple_choice" => false, "created_at" => now()],
            
            ["exercise_id" => "37", "prompt" => "I'm sure it was a surprise when you saw Jake at the party.", "before_prompt" => "You", "after_prompt" => "see Jake at the party.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "37", "prompt" => "This is a very dry part of the country.", "before_prompt" => "In this part of the country", "after_prompt" => "rains.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "37", "prompt" => "In the morning I have a twenty-minute walk to school.", "before_prompt" => "In the morning", "after_prompt" => "to walk to school.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "37", "prompt" => "It was impossible for use to go to school because of the bus strike.", "before_prompt" => "The bus strike", "after_prompt" => "to school.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "37", "prompt" => "On hearing the fire alarm, you must leave the building as quickly as possible.", "before_prompt" => "You must leave the building", "after_prompt" => "the fire alarm.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "37", "prompt" => "I am trying to study, so would you mind not making that noise?", "before_prompt" => "I am trying to study, so I", "after_prompt" => "make that noise.", "is_multiple_choice" => false, "created_at" => now()],
            
            ["exercise_id" => "38", "prompt" => "This time I didn't manage to win first prize.", "before_prompt" => "I didn't", "after_prompt" => "first prize this time.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "38", "prompt" => "Last night the theatre was almost empty.", "before_prompt" => "Last night", "after_prompt" => "the theatre.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "38", "prompt" => "My elder sister likes to look after small children.", "before_prompt" => "My elder sister enjoys", "after_prompt" => "small children", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "38", "prompt" => "I've never heard such a silly story!", "before_prompt" => "That story is", "after_prompt" => "heard!", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "38", "prompt" => "Amy asked what my reaction to her decision was.", "before_prompt" => "Amy asked", "after_prompt" => "her decision", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "38", "prompt" => "The meeting probably won't last more than a few minutes.", "before_prompt" => "The meeting", "after_prompt" => "on for more than a few minutes.", "is_multiple_choice" => false, "created_at" => now()],
            
            ["exercise_id" => "39", "prompt" => "They think the jewel thief is planning another crime.", "before_prompt" => "The jewel thief", "after_prompt" => "planning another crime.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "39", "prompt" => "'Can you lend me some money, Marta?' asked David.", "before_prompt" => "David asked Marta", "after_prompt" => "some money.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "39", "prompt" => "I saw the race begin because I arrived at the stadium on time.", "before_prompt" => "If i hadn't arrived at the stadium on time, I", "after_prompt" => "of the race.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "39", "prompt" => "I think you ought to decide right now.", "before_prompt" => "If I", "after_prompt" => "a decision right now.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "39", "prompt" => "The rider of the stolen motorbike was a man aged about 25.", "before_prompt" => "The stolen motorbike", "after_prompt" => "a man aged about 25.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "39", "prompt" => "I'm sorry I went out last night.", "before_prompt" => "I", "after_prompt" => "out last night.", "is_multiple_choice" => false, "created_at" => now()],
            
            ["exercise_id" => "40", "prompt" => "Please don't leave the building because we might need to speak to you again.", "before_prompt" => "Please don't leave the building", "after_prompt" => "to speak to you again.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "40", "prompt" => "'Don't be late again, Jamie', said the teacher.", "before_prompt" => "The teacher", "after_prompt" => "late again.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "40", "prompt" => "A well-known director is making a film of Jennifer Shaw's latest novel.", "before_prompt" => "A film of Jennifer Shaw's latest novel", "after_prompt" => "a well-known director.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "40", "prompt" => "We hadn't expected the weather to be so bad.", "before_prompt" => "The weather", "after_prompt" => "expected.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "40", "prompt" => "I had trouble printing documents from the computer.", "before_prompt" => "I", "after_prompt" => "documents from the computer.", "is_multiple_choice" => false, "created_at" => now()],
            ["exercise_id" => "40", "prompt" => "They don't let us use mobile phones in the library.", "before_prompt" => "In the library,", "after_prompt" => "use mobile phones.", "is_multiple_choice" => false, "created_at" => now()],

        ]);
    }
}
